### ISSUE TITLE
Mongostore problem

### ISSUE THREAD

**Issue by kentyap** [kcbanner/connect-mongo#178]
I used connect-mongo to store my Sessions as follows
// Express MongoDB session storage
global.mgs = new mongoStore({
   db: db.connection.db,
   collection: config.sessionCollection
});

global.dbsession = session({
   saveUninitialized: true,
   resave: true,
   secret: config.sessionSecret,
   store: global.mgs

});

   app.use(global.dbsession);

However I fail to retrieve the sessions using the following command.
global.mgs.get(counter.sessionid, function (err, session) {
   if (err || !session) {
      console.log('fail to find sessid');
   } else {
      console.log('session ', session.sessionid);
   }
});

Is there any documentation to use the mongostore to retrieve and save to the Mongodb directly.

I am trying to terminate another login sessions to prevent multiple session using the same login ID.

**Comment by Signus** [comment]
I would suggest using a connector like `Mongoose` and implementing a schema and model in order to use Mongoose's `findOne()`, `findOneAndModify()` or `update()`. 

For example:

  1) Set up your schema and model

```
var mongoose = require('mongoose');

var Schema = mongoose.Schema;
var userSessionSchema = new Schema({
	sessionID: String, {
		type: String,
		unique, true
	},
	username: String,
	email: String
});

var userSession = mongoose.model('session', userSessionSchema);
```

  2) Using the model, locate the appropriate record:

```
// Finds one record from the mongo store matching your criteria
userSession.findOne({ sessionID: req.session.sessionID }, function(err, session) {
    if (!session)
        // destroy the session here
        console.log('No session found matching your criteria');
    else
        console.log(session);
});
```

Aside from that I know of no way of using `connect-mongo` to search for the data directly, as it takes care of updating data from your session into the datastore automatically and is meant to be a CRUD abstraction from the user.

**Comment by jdesboeufs** [comment]
The `get` interface must be used with the identifier generated by connect-mongo, not by your custom one.
I think your attribute `sessionid` duplicates internal `_id`.
